### PR TITLE
Replacing instances of rc_test with bsd_test

### PR DESCRIPTION
**Pull request by rishabh27892**

### CODE REVIEW

**Comment by christiand992** [comment]
It looks like line #74 is still using the rc_test function to make a mountpoint for the SMB share, I believe it should also be using the bsd_test function.

**Review by christiand992 — CHANGES_REQUESTED** [review]
It looks like line #76 is still using the rc_test function to make a mountpoint for the SMB share, I believe it should also be using the bsd_test function.

**Comment by pkgdemon** [comment]
@rishabh27892 I am thinking we should have you do this over.  As a single pull request for all, and more descriptive info in each commit message.  Right now it is difficult to determine which files are being touched in each pull without specifying something like "converting instances of rc_test to bsd_test in ad_bsd".  I am also thinking the commit message should be more meaninful if we ever need to cherry-pick, or revert.  Also it is hard to see without descriptions if you had yet corrected what @christiand992 pointed out what missed on line 76.
 @christiand992 Do you have any preference regarding commit messages, or mutiple vs single pull request as well for these changes?

**Comment by christiand992** [comment]
I typically do as much work towards completing a project/task as possible in a branch and wait until I'm done, or when I have items that need reviewing before I complete the task, then issue a pull request. Either way, you can also add/stack commits on an existing pull request, so if you want feedback before the task is complete, that is the route I would go - using the same pull request as work gets completed.----- Original Message -----

**Comment by rishabh27892** [comment]
I am closing all the previous pull requests, will make changes in my repo, commit for each file with a bit more descriptive explanation (adding file name) and finally sending 1 pull request.  Thanks a lot for helping me with this @pkgdemon  and @christiand992

**Pull request closed without merging**
